apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        env:
          - name: PMA_HOST
            valueFrom:
              configMapKeyRef:
                name: phpadmin-config
                key: PMA_HOST
          - name: PMA_PORT
            valueFrom:
              configMapKeyRef:
                name: phpadmin-config
                key: PMA_PORT
          - name: PMA_USER
            valueFrom:
              configMapKeyRef:
                name: phpadmin-config
                key: PMA_USER
          - name: PMA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: phpadmin-secret
                key: PMA_PASSWORD
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  ports:
    - port: 80
  selector:
    app: phpmyadmin
  type: LoadBalancer
